<script setup lang="ts">
import type { SalesBookingForm } from '@/services/salesExecutive.service'
defineProps<{ form: SalesBookingForm }>()
defineEmits<{ close: [] }>()
const approachLabels: Record<string, string> = { spin: 'Método SPIN', automatic_paragraph: 'Párrafo automático', direct_service: 'Habla directo del servicio', catalog: 'Envía catálogo' }
const objectionLabels: Record<string, string> = { price_no_response: 'No responden tras el precio', think_about_it: 'Lo va a pensar', out_of_budget: 'Fuera de presupuesto', curiosity: 'Solo curiosidad', other: 'Otra objeción' }
function date(value: string) { return new Date(value).toLocaleString('es-EC', { day: 'numeric', month: 'long', year: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: 'America/Guayaquil' }) }
function money(value: number) { return new Intl.NumberFormat('es-EC', { style: 'currency', currency: 'USD' }).format(value) }
function month(value: string) { return new Date(value).toLocaleDateString('es-EC', { month: 'long', year: 'numeric', timeZone: 'America/Guayaquil' }) }
</script>

<template>
  <Transition name="details" appear><div class="details" @click.self="$emit('close')"><section><button @click="$emit('close')"><i class="fa-solid fa-xmark"></i></button><span>Formulario comercial</span><h2>{{ form.client.name }}</h2><p><i class="fa-solid fa-inbox"></i>Ingresó al proceso: {{ date(form.submittedAt) }} · {{ form.workspace.name }}</p><div><aside class="details__performance"><small>Ventas al ingresar al proceso</small><div><article><span>{{ month(form.billing.monthlyComparison.currentMonthStart) }}</span><strong>{{ money(form.billing.monthlyComparison.currentMonthRevenue) }}</strong><em>Hasta la fecha de ingreso</em></article><article><span>{{ month(form.billing.monthlyComparison.previousMonthStart) }}</span><strong>{{ money(form.billing.monthlyComparison.previousMonthRevenue) }}</strong><em>Comparativo mismo corte</em></article></div><b :class="{ 'is-positive': (form.billing.monthlyComparison.changePercent || 0) >= 0 }"><i :class="(form.billing.monthlyComparison.changePercent || 0) >= 0 ? 'fa-solid fa-arrow-trend-up' : 'fa-solid fa-arrow-trend-down'"></i>{{ form.billing.monthlyComparison.changePercent === null ? 'Sin base comparativa' : `${form.billing.monthlyComparison.changePercent.toFixed(1)}% vs. mes anterior` }}</b></aside><article><small>Cómo aborda la venta</small><strong>{{ approachLabels[form.diagnostic.salesApproach] || form.diagnostic.salesApproach }}</strong></article><article><small>Objeción principal</small><strong>{{ form.diagnostic.commonObjection === 'other' ? form.diagnostic.otherObjection : objectionLabels[form.diagnostic.commonObjection] }}</strong></article><aside><small>Facturación hasta el envío</small><div class="details__billing"><strong>{{ money(form.billing.totalRevenue) }}</strong><span>{{ form.billing.registeredDays }} días registrados · ROAS {{ form.billing.roas.toFixed(2) }}</span><em>Gasto Meta: {{ money(form.billing.totalMetaSpend) }}</em></div><div class="details__billing-days"><span v-for="entry in form.billing.entries" :key="entry.date">{{ date(entry.date) }}<strong>{{ money(entry.amount) }}</strong></span><p v-if="!form.billing.entries.length">No hay facturación registrada hasta este día.</p></div></aside><aside><small>Evidencias compartidas</small><a v-for="file in form.diagnostic.evidence" :key="file.url" :href="file.url" target="_blank" rel="noopener"><i :class="file.mimeType === 'application/pdf' ? 'fa-solid fa-file-pdf' : 'fa-solid fa-image'"></i><span>{{ file.name }}<em v-if="file.description">{{ file.description }}</em></span><i class="fa-solid fa-arrow-up-right-from-square"></i></a></aside></div></section></div></Transition>
</template>

<style scoped lang="scss">
.details { position: fixed; z-index: 1000; inset: 0; display: flex; align-items: center; justify-content: center; padding: 1rem; background: rgba($primary-dark,.72); }.details > section { position: relative; display: flex; width: min(100%,680px); max-height: 90vh; flex-direction: column; gap: 1rem; overflow: auto; padding: 2rem; border-radius: 22px; background: $white; }.details h2 { margin: 0; color: $primary-dark; font-size: 1.8rem; }.details > section > span, .details small { color: $primary; font-size: .72rem; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; }.details p { margin: 0; color: $text-secondary; }.details p i { margin-right: .5rem; color: $primary; }.details > section > div { display: flex; flex-direction: column; gap: .8rem; }.details article, .details aside { display: flex; flex-direction: column; gap: .4rem; padding: 1rem; border-radius: 14px; background: rgba($primary,.05); }.details strong { color: $primary-dark; }.details a { display: flex; align-items: center; gap: .7rem; padding: .75rem; border-radius: 10px; color: $primary-dark; background: $white; text-decoration: none; }.details a > span { display: flex; flex: 1; flex-direction: column; gap: .15rem; }.details em { color: $text-secondary; font-size: .78rem; font-style: normal; }.details button { position: absolute; top: 1rem; right: 1rem; display: flex; align-items: center; justify-content: center; width: 2.2rem; height: 2.2rem; padding: 0; border: 0; border-radius: 50%; color: $text-secondary; background: rgba($primary-dark,.08); cursor: pointer; }.details__billing { display: flex; flex-wrap: wrap; align-items: baseline; gap: .5rem; padding: .75rem; border-radius: 10px; background: $white; }.details__billing > strong { font-size: 1.35rem; }.details__billing-days { display: flex; flex-direction: column; max-height: 12rem; overflow: auto; border-radius: 10px; background: $white; }.details__billing-days > span { display: flex; justify-content: space-between; gap: 1rem; padding: .55rem .7rem; border-bottom: 1px solid rgba($primary-dark,.06); color: $text-secondary; font-size: .78rem; }.details-enter-active, .details-leave-active { transition: opacity .2s ease; }.details-enter-from, .details-leave-to { opacity: 0; }
.details__performance > div { display: flex; flex-wrap: wrap; gap: .7rem; }.details__performance article { flex: 1 1 180px; padding: .8rem; background: $white; }.details__performance article span { color: $text-secondary; font-size: .72rem; font-weight: 800; text-transform: capitalize; }.details__performance article strong { font-size: 1.2rem; }.details__performance b { display: inline-flex; align-items: center; gap: .4rem; color: #b45309; font-size: .82rem; }.details__performance b.is-positive { color: #16714b; }
</style>
